---
collections:
  - name: britishgeologicalsurvey.linux
    source: <redacted>
    type: git
    version: 0.4.12

roles:
  - name: geerlingguy.docker # what you would like for the role to be called
    src: <redacted> # the http link if scm git/hg or galaxy namespace of the role
    scm: git # git or hg if src is a link
    version: 7.1.0 # tag, commit-ish, or branch name
